import test from 'node:test';import assert from 'node:assert/strict';
import {sourceUrl,arabicPassage,readSource,readOfficialSource,findHadithSource,libraryMatch} from '../lib/hadith-source.mjs';
import {extractIsnad,validateExtraction,hasIsnad,literalExtraction,completeExplicitEndpoint} from '../lib/isnad-extractor.mjs';
const env={AI_KEY_GEMINI:'test-only-key'};
const response=value=>Response.json({status:'completed',steps:[{type:'model_output',content:[{type:'text',text:JSON.stringify(value)}]}]});
const full='حدثنا محمد بن سنان، قال حدثنا فليح، ح وحدثني إبراهيم بن المنذر، قال حدثنا محمد بن فليح، قال حدثني أبي قال، حدثني هلال بن علي، عن عطاء بن يسار، عن أبي هريرة، قال بينما النبي في مجلس يحدث القوم.';
const names=['محمد بن سنان','فليح','إبراهيم بن المنذر','محمد بن فليح','أبي','هلال بن علي','عطاء بن يسار','أبي هريرة','النبي'];
const candidate=()=>({refuse:false,nodes:names.map((nameQuote,i)=>({id:'n'+i,nameQuote,occurrence:0,uncertain:['فليح','أبي'].includes(nameQuote)})),paths:[{nodeIds:['n0','n1'],linkQuotes:[]},{nodeIds:['n2','n3','n4','n5','n6','n7','n8'],linkQuotes:[]}],matnQuote:'بينما النبي في مجلس يحدث القوم.'});
test('the branch-switch example preserves literal paths but joins their shared identity only using the reviewed printed source and lineage',async()=>{let calls=0;const result=await extractIsnad({text:full,locale:'ar'},env,async(url,init)=>{if(++calls===1)return response(candidate());const {items}=JSON.parse(JSON.parse(init.body).input);return response({checks:items.map(i=>({id:i.id,supported:true}))});});assert.equal(result.status,'draft');assert.equal(result.draft.paths.length,2);assert.equal(result.incompleteBranches,0);assert.equal(result.draft.nodes.find(n=>n.nameQuote==='أبي').uncertain,true);assert.ok(result.data.narrators.every(n=>!n.reliability&&!n.role));assert.ok(!result.draft.paths.flatMap(p=>p.links).some(l=>l.from==='n1'&&l.to==='n2'));assert.equal(result.identityReview.profileUrl,'https://shamela.ws/book/8609/428');assert.equal(result.data.hadiths[0].chains[0].nodes.at(-1),result.data.hadiths[0].chains[1].nodes.at(-1));});

test('similar short names in another input cannot borrow the reviewed Bukhari identity join',async()=>{const changed=full.replace('هلال بن علي','رجل آخر');const result=await extractIsnad({text:changed,modelId:'local'},{});assert.equal(result.identityReview,undefined);assert.equal(result.incompleteBranches,1);assert.ok(result.data.narrators.some(n=>n.name==='أبي'));assert.ok(!result.data.sources.some(s=>s.url==='https://shamela.ws/book/1681/112'));});
test('a missing literal terminal speaker is included only when its explicit narration context passes the original span validator',()=>{const r=candidate();r.nodes=r.nodes.slice(0,-1);r.paths[1].nodeIds.pop();r.paths.forEach(p=>p.linkQuotes=p.nodeIds.slice(0,-1).map((id,i)=>{const a=r.nodes.find(n=>n.id===id),b=r.nodes.find(n=>n.id===p.nodeIds[i+1]);return full.slice(full.indexOf(a.nameQuote),full.indexOf(b.nameQuote)+b.nameQuote.length);}));const draft=validateExtraction(full,r);assert.ok(draft);const fixed=completeExplicitEndpoint(full,draft);assert.equal(fixed.nodes.at(-1).nameQuote,'النبي');assert.equal(fixed.paths[1].nodeIds.at(-1),'explicit-prophet');const noSpeaker=full.replace('النبي','رجل');assert.equal(completeExplicitEndpoint(noSpeaker,draft),draft);});
test('a printed branch switch cannot become a fabricated sequential edge',()=>{const r=candidate();r.paths=[{nodeIds:r.nodes.map(n=>n.id),linkQuotes:r.nodes.slice(0,-1).map((n,i)=>full.slice(full.indexOf(n.nameQuote),full.indexOf(r.nodes[i+1].nameQuote)+r.nodes[i+1].nameQuote.length))}];assert.equal(validateExtraction(full,r),null);assert.ok(hasIsnad(full));});
test('source retrieval is allowlisted, bounded, and never forwards secrets to another host',async()=>{for(const url of ['http://sunnah.com/bukhari:59','https://sunnah.com.evil.test/bukhari:59','https://sunnah.com@evil.test/bukhari:59','https://shamela.ws/book/1681/112?key=x','https://sunnah.com:8080/bukhari:59','https://127.0.0.1/bukhari:59'])assert.equal(sourceUrl(url),null);assert.equal(sourceUrl('https://shamela.ws/book/1681/112'),'https://shamela.ws/book/1681/112');let calls=0;await assert.rejects(()=>readSource('https://shamela.ws/book/1681/112',async(url,init)=>{calls++;assert.equal(init.redirect,'manual');assert.ok(!init.headers['x-api-key']);return new Response(null,{status:302,headers:{location:'https://evil.test'}});}),{code:'SOURCE_UNAVAILABLE'});assert.equal(calls,1);await assert.rejects(()=>readSource('https://evil.test',()=>{throw Error('must not fetch');}),{code:'INPUT'});});
test('matn-only library input uses reviewed chains without requiring a model key or generating identities',async()=>{const r=await extractIsnad({text:'لا تغضب',locale:'ar'}, {},()=>{throw Error('must not fetch');});assert.equal(r.status,'recorded');assert.ok(r.data.hadiths[0].chains.length);assert.ok(libraryMatch('لا تغضب'));assert.equal(libraryMatch('هذا ليس حديثا مسجلا'),null);});
test('new source pages must contain an explicit matching chain, and blocked pages fail closed',async()=>{const html='<div class="nass">'+full+'</div>';assert.equal(arabicPassage(html),full);assert.equal((await findHadithSource('https://shamela.ws/book/1681/112',async()=>new Response(html))).text,full);assert.equal(await findHadithSource('https://shamela.ws/book/1681/112',async()=>new Response('<div class="nass">هذا متن طويل دون سلسلة للرواة أو صيغ الإسناد.</div>')),null);await assert.rejects(()=>findHadithSource('https://shamela.ws/book/1681/112',async()=>new Response('Just a moment',{status:403})),{code:'SOURCE_UNAVAILABLE'});});
test('extraction correction retains the same literal-source rules and obtains a fresh check',async()=>{let calls=0;const r=await extractIsnad({text:full},env,async(url,init)=>{calls++;if(calls===1){const r=candidate();r.nodes[0].nameQuote='راو مخترع';return response(r);}if(calls===2){assert.ok(JSON.parse(JSON.parse(init.body).input).correction);return response(candidate());}const {items}=JSON.parse(JSON.parse(init.body).input);return response({checks:items.map(i=>({id:i.id,supported:true}))});});assert.equal(calls,3);assert.equal(r.status,'draft');});

test('explicit Arabic formulas still draw a disclosed literal tree when the model key is unavailable',async()=>{const direct=literalExtraction(full);assert.ok(direct);assert.equal(direct.paths.length,2);const r=await extractIsnad({text:full,modelId:'local'},{});assert.equal(r.engine,'parser');assert.equal(r.providerError,'UNAVAILABLE');assert.equal(r.draft.paths.length,2);assert.equal(literalExtraction('هذا متن لا يحوي سلسلة للرواة'),null);});
test('an authentication outage can only fall back to literal supplied evidence, never to a recalled chain',async()=>{const r=await extractIsnad({text:full},env,async()=>Response.json({}, {status:401}));assert.equal(r.engine,'parser');assert.equal(r.providerError,'AUTH');assert.ok(r.draft.nodes.every(n=>full.includes(n.nameQuote)));});
import {englishMatn} from '../lib/hadith-english.mjs';import {catalog} from '../lib/catalog.mjs';
test('English source text and titles can match a reviewed report without translating the quotation',()=>{const h=catalog.hadiths[0];assert.equal(libraryMatch(englishMatn(h)).data.hadiths[0].id,h.id);assert.ok(hasIsnad('Narrated Ahmad: I heard Sufyan who said he heard his father.'));});
test('diacritics and Unicode prefixes cannot shift literal name offsets',()=>{const r=literalExtraction('📖 حدثنا أَحْمَدُ، قال حدثنا سُفْيَانُ، عن أَبِيهِ قال: المتن الأصلي.');assert.ok(r);for(const n of r.nodes)assert.equal('📖 حدثنا أَحْمَدُ، قال حدثنا سُفْيَانُ، عن أَبِيهِ قال: المتن الأصلي.'.slice(n.start,n.end),n.nameQuote);});

