'use client';
import { useEffect, useRef, useState } from 'react';
import { BookOpen, Network, Search, ChevronDown, ShieldCheck, MessageCircle, X, Send, ExternalLink, GitBranch, Library, Info } from 'lucide-react';
import { normalize } from '@/lib/catalog.mjs';
import ThemeToggle from './theme-toggle';
import Link from 'next/link';
import SanadMap from './sanad-map';
import type {Source,Sourced,Hadith,Data} from '@/lib/catalog-types';
import {narratorTone,TRUST_LABELS} from '@/lib/sanad-map.mjs';

type Reply={question:string;answer:string;status:string;engine:string;notice?:string;fallbackReason?:string;narrator?:{id:string;name:string};sources:Source[];claims?:{id:string;text:string;sourceIds:string[]}[]};
const prompts=['اشرح لي هذا السند','من روى عن من؟','من هذا الراوي؟','أعطني نبذة عن هذا الراوي','متى توفي هذا الراوي؟','ما مصدر هذا الحديث؟','ما حكم هذا الراوي؟','ما حكم هذا الإسناد؟'];
function SourceList({ids,data}:{ids:string[];data:Data}){return <div className="sources">{data.sources.filter(s=>ids.includes(s.id)).map(s=><div key={s.id}><strong>{s.title}</strong><span>{s.reference}</span>{s.url&&<a href={s.url} target="_blank" rel="noopener noreferrer">افتح المصدر <ExternalLink size={14}/></a>}</div>)}</div>;}

const gradeLabels={sahih:'صحيح',weak:'ضعيف',fabricated:'موضوع'};
function GradeBadge({hadith}:{hadith:Hadith}){const grade=hadith.judgement?.grade;return grade?<span className={`hadith-grade grade-${grade}`}>{gradeLabels[grade]}</span>:null;}

export default function Explorer({data}:{data:Data}){
  const [search,setSearch]=useState(''),[hid,setHid]=useState(''),[cid,setCid]=useState(''),[nid,setNid]=useState('');
  const [view,setView]=useState('tree'),[about,setAbout]=useState(false),[zoom,setZoom]=useState(1),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[replies,setReplies]=useState<Reply[]>([]),[model,setModel]=useState('local');
  const [models,setModels]=useState([{id:'local',label:'الإجابة من المصادر · دون نموذج خارجي',ready:true}]);
  const abort=useRef<AbortController|null>(null), revision=useRef(0);
  const dialog=useRef<HTMLElement|null>(null);
  useEffect(()=>{
    if(!about)return;
    const previous=document.activeElement as HTMLElement|null;
    const items=()=>Array.from(dialog.current?.querySelectorAll<HTMLElement>('button,a[href],input,select,[tabindex="0"]')||[]);
    items()[0]?.focus();
    const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){setAbout(false);return;}if(e.key==='Tab'){const list=items(),first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
    document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.focus();};
  },[about]);
  useEffect(()=>{const controller=new AbortController();fetch('/api/models',{signal:controller.signal}).then(r=>r.json() as Promise<{models:typeof models}>).then(d=>{if(Array.isArray(d.models)){setModels(d.models);const external=d.models.find(m=>m.id!=='local'&&m.ready);if(external)setModel(external.id);}}).catch(()=>{});return()=>{controller.abort();abort.current?.abort();};},[]);
  const h=data.hadiths.find(h=>h.id===hid),c=h?.chains.find(c=>c.id===cid),n=data.narrators.find(n=>n.id===nid);
  const filtered=data.hadiths.filter(h=>normalize(`${h.title} ${h.matn} ${h.chains.flatMap(c=>c.nodes).map(id=>data.narrators.find(n=>n.id===id)?.name).join(' ')}`).includes(normalize(search)));
  function reset(){abort.current?.abort();revision.current++;setBusy(false);setReplies([]);setError('');setNid('');setZoom(1);}
  function choose(h:Hadith){reset();setQuestion('');setHid(h.id);setCid(h.chains[0].id);}
  function chooseNarrator(id:string){abort.current?.abort();revision.current++;setBusy(false);setReplies([]);setError('');setQuestion('');setNid(id);}
  async function ask(value=question){if(!value.trim()||busy||!h||!c)return;const turn=revision.current;abort.current=new AbortController();setBusy(true);setError('');
    try {const r=await fetch('/api/assistant',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:value,hadithId:h.id,chainId:c.id,narratorId:nid||undefined,modelId:model}),signal:abort.current.signal});const result=await r.json() as Reply & {error?:string};if(!r.ok)throw new Error(result.error||'تعذر إرسال السؤال');if(turn!==revision.current)return;setReplies(p=>[...p.slice(-9),{...result,question:value}]);setQuestion('');}
    catch(e){if(turn===revision.current && (e as Error).name!=='AbortError')setError((e as Error).message||'تعذر الاتصال. أعد المحاولة.');}finally{if(turn===revision.current)setBusy(false);}
  }
  return <>
    <header className="header"><Link className="brand" href="/" aria-label="شجرة الأسانيد الرئيسية"><span className="brand-icon"><GitBranch size={26}/></span><span>شجرة الأسانيد<small>رحلة الحديث، راوٍ بعد راوٍ</small></span></Link><nav><button className="nav-active" onClick={()=>{setAbout(false);setView('tree');}}><Network size={18}/> استكشاف الأسانيد</button><button onClick={()=>setAbout(true)}><Library size={18}/> عن المشروع والمصادر</button></nav><div className="header-actions"><span className="educational">مساحة للتعلّم</span><ThemeToggle/></div></header>
    <main><div className="page-heading"><div><span className="eyebrow">من النص إلى العلاقة</span><h1>تتبّع سند الحديث</h1><p>اختر حديثًا، واستكشف كيف ترتبط أسماء رواته.</p></div><div className="data-count"><BookOpen size={20}/><b>{data.hadiths.length.toLocaleString('ar')}</b><span>حديث في المكتبة</span></div></div>
    <div className="workspace">
      <aside className="library panel"><div className="panel-title"><h2><BookOpen size={19}/> مكتبة الأحاديث</h2><span className="count">{data.hadiths.length.toLocaleString('ar')}</span></div><label className="search"><Search size={18}/><input aria-label="ابحث عن حديث أو راوٍ" placeholder="ابحث عن حديث أو راوٍ…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="grade-summary" aria-label="توزيع أحكام الأحاديث">{Object.entries(gradeLabels).map(([grade,label])=><span className={`hadith-grade grade-${grade}`} key={grade}>{data.hadiths.filter(h=>h.judgement?.grade===grade).length.toLocaleString('ar')} {label==='صحيح'?'صحيحة':label==='ضعيف'?'ضعيفة':'موضوعة'}</span>)}</div><div className="library-list">{filtered.map((item,i)=><button className={`hadith-item ${hid===item.id?'selected':''}`} key={item.id} onClick={()=>choose(item)}><span className="item-number">{(i+1).toLocaleString('ar',{minimumIntegerDigits:2})}</span><span><strong>{item.title}</strong><GradeBadge hadith={item}/><small>{data.sources.find(s=>s.id===item.sourceIds[0])?.reference}</small></span><GitBranch size={17}/></button>)}{!filtered.length&&<div className="library-empty"><Library size={32}/><strong>{search?'لا توجد نتائج':'المكتبة بانتظار أحاديثكم'}</strong><p>{search?'جرّب كلمة أخرى أو امسح البحث.':'ستظهر هنا الأحاديث المعتمدة بعد إضافتها مع مصادرها.'}</p>{search&&<button className="text-button" onClick={()=>setSearch('')}>مسح البحث</button>}</div>}</div><div className="library-footer"><ShieldCheck size={19}/><p>كل علاقة في الشجرة مرتبطة بمصدرها.</p></div></aside>
      <section className="explorer panel" aria-label="استكشاف السند"><div className="explorer-top"><div><span className="eyebrow">{h?'الحديث المختار':'مساحة الاستكشاف'}</span><h2>{h?.title||'شجرة الأسانيد'}</h2>{h&&<GradeBadge hadith={h}/>}</div>{h&&<span className="source-tag">{data.sources.find(s=>s.id===h.sourceIds[0])?.reference}</span>}</div><div className="tabs" role="tablist" aria-label="عرض الحديث"><button role="tab" aria-selected={view==='tree'} className={view==='tree'?'active':''} onClick={()=>setView('tree')}><Network size={17}/> شجرة السند</button><button role="tab" aria-selected={view==='text'} className={view==='text'?'active':''} onClick={()=>setView('text')}><BookOpen size={17}/> المتن والمصدر</button></div>
      {view==='tree'?<>{h?.judgement&&(h.judgement.grade==='weak'||h.judgement.grade==='fabricated')&&<div className={`hadith-notice grade-${h.judgement.grade}`} role="note"><strong>{h.judgement.grade==='fabricated'?'رواية موضوعة — النسبة إلى النبي ﷺ لا تثبت':'رواية ضعيفة — الحكم يخص الطريق المذكور'}</strong><p>{h.judgement.text}</p><SourceList ids={h.judgement.sourceIds} data={data}/></div>}<div className="tree-toolbar"><span><i className="line-key"/> يروي عن</span>{h&&<label className="chain-choice">المسار <select aria-label="اختر السند" value={cid} onChange={e=>{reset();setCid(e.target.value);}}>{h.chains.map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select><ChevronDown size={14}/></label>}<span className="toolbar-note">{h?'اضغط الاسم للاستكشاف':'ابدأ باختيار حديث من المكتبة'}</span></div>{c?.note&&<div className="chain-note"><p>{c.note.text}</p><SourceList ids={c.note.sourceIds} data={data}/></div>}{c&&h?<SanadMap key={`${h.id}:${c.id}`} data={data} hadith={h} chain={c} selected={nid} onSelect={chooseNarrator} zoom={zoom} onZoom={setZoom}/>:<div className="tree-canvas is-empty"><div className="empty-tree"><Network size={36}/><h3>اختر حديثًا لتبدأ</h3><p>اختر حديثًا من المكتبة لعرض سنده وتتبع رواته خطوة بخطوة.</p></div></div>}<div className="canvas-footer"><span><GitBranch size={16}/>{c?`${c.nodes.length.toLocaleString('ar')} أسماء في هذا المسار`:'السند يظهر بعد اختيار الحديث'}</span><span>الترتيب كما في المصدر</span></div></>:<div className="text-view">{h?<>{h.judgement&&<div className={`hadith-notice grade-${h.judgement.grade||'unknown'}`} role="note"><h3>{h.judgement.grade==='fabricated'?'رواية موضوعة — النسبة إلى النبي ﷺ لا تثبت':'الحكم المنقول على الرواية'}</h3><p>{h.judgement.text}</p><SourceList ids={h.judgement.sourceIds} data={data}/></div>}<span className="eyebrow">{h.judgement?.grade==='fabricated'?'نص الرواية الموضوعة':'متن الحديث'}</span><blockquote>{h.matn}</blockquote><h3>المصدر</h3><SourceList ids={h.sourceIds} data={data}/><h3>مصادر الأسانيد</h3>{h.chains.map(c=><div key={c.id}><h4>{c.label}</h4>{c.isnad&&<div className="isnad-original"><small>نص الإسناد كما في المصدر</small><p>{c.isnad}</p></div>}{c.note&&<p className="isnad-note">{c.note.text}</p>}<SourceList ids={c.sourceIds} data={data}/></div>)}</>:<div className="text-empty"><BookOpen size={36}/><h3>اختر حديثًا لعرض المتن</h3><p>اختر من المكتبة، وسيظهر هنا نص الحديث ومصدره.</p></div>}</div>}
      </section>
      <aside className="details panel"><div className="panel-title"><h2><Info size={19}/> بطاقة الراوي</h2>{n&&<button aria-label="إغلاق بطاقة الراوي" onClick={()=>chooseNarrator('')}><X size={17}/></button>}</div>{n&&c?<div className="narrator-detail"><span className="eyebrow">الاسم في المصدر</span><h3>{n.name}</h3><span className="position">الموضع {(c.nodes.indexOf(n.id)+1).toLocaleString('ar')} في هذا المسار</span>{[['التعريف',n.bio],['الكنية',n.kuniya],['الولادة',n.birth],['الوفاة',n.death],['الطبقة',n.classification],['الفترة',n.period]].filter(([title,field])=>field||['التعريف','الطبقة'].includes(title as string)).map(([title,field])=><div className="detail-field" key={title as string}><h4>{title as string}</h4>{field?<><p>{(field as Sourced).text}</p><SourceList ids={(field as Sourced).sourceIds} data={data}/></>:<p className="unavailable">لا توجد معلومة موثقة في البيانات الحالية.</p>}</div>)}<div className="detail-field"><h4>التوثيق في المصادر</h4>{n.reliability?<><span className={`trust-badge tone-${narratorTone(n)}`}>{TRUST_LABELS[narratorTone(n) as keyof typeof TRUST_LABELS]}</span><p>{n.reliability.text}</p><SourceList ids={n.reliability.sourceIds} data={data}/></>:n.role?<><p>{n.role.type==='prophet'?'النبي ﷺ؛ تعرض هويته مستقلة عن تصنيفات الرواة.':'صحابي؛ يعرض بهذه الصفة مستقلة عن أقوال الجرح والتعديل.'}</p><SourceList ids={n.role.sourceIds} data={data}/></>:<p className="unavailable">لم يُدخل حكم موثق لهذا الراوي.</p>}</div><h4>علاقته في السند</h4>{c.links.filter(l=>l.from===nid||l.to===nid).map(l=><div key={l.from+l.to} className="relation"><p>{data.narrators.find(n=>n.id===l.from)?.name} <span>يروي عن</span> {data.narrators.find(n=>n.id===l.to)?.name}</p><SourceList ids={l.sourceIds} data={data}/></div>)}<h4>مرجع الاسم</h4><SourceList ids={n.sourceIds} data={data}/></div>:<div className="detail-empty"><span className="detail-outline"><Info size={24}/></span><h3>تعرّف إلى الراوي</h3><p>اضغط على اسم في الشجرة لعرض معلوماته وعلاقته بالسند ومصدر كل معلومة.</p></div>}<div className="detail-footer"><ShieldCheck size={17}/><span>المعلومة غير المتوفرة لا تُستكمل بالتخمين.</span></div></aside>
    </div>
    <section className="assistant panel"><div className="assistant-intro"><div className="assistant-icon"><MessageCircle size={23}/></div><div><h2>اسأل عن السند</h2><p>إجابات من بيانات الحديث المختار ومصادره فقط.</p></div><span className="grounded"><ShieldCheck size={16}/> مرتبط بالمصادر</span></div><div className="assistant-body"><div className="assistant-settings"><label>طريقة الإجابة<select aria-label="اختر نموذج المساعد" value={model} onChange={e=>setModel(e.target.value)}>{models.map(m=><option key={m.id} value={m.id} disabled={!m.ready}>{m.label}{!m.ready?' · غير مفعّل':''}</option>)}</select></label><p>{model==='local'?'الوضع الحالي يعرض المعلومات مباشرة من المصادر، دون استدعاء نموذج.':'يتحقق النموذج من الأدلة المتاحة، وتعرض الإجابة من المعلومات المسجلة فقط.'}</p></div><p className="narrator-context">{n?`الراوي المختار: ${n.name}`:'اختر راوياً من الشجرة للأسئلة عنه، أو اكتب اسمه المميز في السؤال.'}</p><div className="prompt-list">{prompts.map(p=><button disabled={!h||busy||(p.includes('الراوي')&&!nid)} key={p} onClick={()=>ask(p)}>{p}</button>)}</div>{replies.length>0&&<div className="conversation" aria-live="polite">{replies.map((r,i)=><div className="exchange" key={i}><div className="question">{r.question}</div><div className={`answer ${r.status}`}><small>{r.status==='answered'?(r.engine==='local'?(r.fallbackReason?'من المصادر مباشرة · الخدمة مشغولة':'من المصادر مباشرة'):'إجابة تحقق منها النموذج'):r.status==='refused'?'لا يتوفر مرجع كافٍ':r.status==='clarification'?'حدد الراوي المقصود':'النموذج غير متاح'}</small>{r.narrator&&<p className="answer-subject">الإجابة عن: {r.narrator.name}</p>}{r.notice&&<p className="fallback-notice">{r.notice}</p>}{r.claims?.length?r.claims.map(f=><div key={f.id}><p>{f.text}</p><SourceList ids={f.sourceIds} data={data}/></div>):<p>{r.answer}</p>}</div></div>)}</div>}{error&&<p className="error" role="alert">{error}</p>}<form className="question-form" onSubmit={e=>{e.preventDefault();ask();}}><input aria-label="سؤالك عن الحديث المختار" value={question} maxLength={500} onChange={e=>setQuestion(e.target.value)} disabled={!h||busy} placeholder={h?'اسأل عن هذا السند أو الراوي المختار…':'اختر حديثًا من المكتبة لتفعيل الأسئلة…'}/><button disabled={!h||busy||!question.trim()} type="submit"><Send size={17}/>{busy?'جارٍ التحقق…':'إرسال'}</button></form><p className="assistant-note">يدعم أسئلة محددة عن السند والراوي المختار والمتن والمصدر. يمتنع عن الأسئلة الأخرى.</p></div></section>
    <footer className="footer"><span>شجرة الأسانيد · تعلّم العلاقات من مصادرها</span><button onClick={()=>setAbout(true)}>المنهج والمصادر <ExternalLink size={14}/></button></footer></main>
    {about&&<div className="modal-backdrop" onClick={()=>setAbout(false)}><section ref={dialog} className="about-modal" role="dialog" aria-modal="true" aria-labelledby="about-title" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setAbout(false)} aria-label="إغلاق"><X size={21}/></button><span className="eyebrow">عن المشروع</span><h2 id="about-title">الحديث في سياق روايته</h2><p>مساحة تعليمية لطلاب الحديث لفهم تسلسل الرواة واستكشاف روابط النقل. يعرض كل مسار بحسب البيانات المسجلة، مع نقل أقوال التوثيق المسجلة ومراجعها، دون توليد أحكام جديدة أو تصحيح الأحاديث.</p><h3>كيف نجيب؟</h3><p>تُحدد الأسئلة المسموحة أولًا، ثم تُسترجع معلومات الحديث المختار. إن فُعّل نموذج، يتحقق من قائمة الأدلة؛ وتُعرض المعلومات المسجلة مع مراجعها. لا تُعرض نصوص حرة ينشئها النموذج.</p><h3>المصادر الحالية</h3>{data.sources.length?<SourceList ids={data.sources.map(s=>s.id)} data={data}/>:<p>لم تُضف مصادر بعد. ننتظر الأحاديث ومراجعها من فريق المشروع.</p>}<h3>حدود النسخة الحالية</h3><p>الأسئلة محصورة في السند والراوي المختار والمتن ومصدره. أي تاريخ أو ترجمة أو حكم غير مسجل يبقى غير متاح. البيانات والمراجع تُراجع قبل إضافتها.</p><button className="primary" onClick={()=>setAbout(false)}>العودة للاستكشاف</button></section></div>}
  </>;
}
